-- Create the Role
USE ROLE USERADMIN;
CREATE ROLE IF NOT EXISTS AIRFLOW_MONITOR_ROLE;

-- Grant to SYSADMIN so you can manage it
USE ROLE SECURITYADMIN;
GRANT ROLE AIRFLOW_MONITOR_ROLE TO ROLE SYSADMIN;

-- Basic Permissions (Monitoring Only)
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE AIRFLOW_MONITOR_ROLE;
GRANT USAGE ON DATABASE YFINANCE_DB TO ROLE AIRFLOW_MONITOR_ROLE;
GRANT USAGE ON SCHEMA YFINANCE_DB.BRONZE TO ROLE AIRFLOW_MONITOR_ROLE;

-- Allow it to see new rows for the Sensor
GRANT SELECT ON TABLE YFINANCE_DB.BRONZE.RAW_STOCK_DATA TO ROLE AIRFLOW_MONITOR_ROLE;

-- Grant to your specific Airflow User
GRANT ROLE AIRFLOW_MONITOR_ROLE TO USER --snowflake user--;s