aws_dbt_snowflake_project:
  outputs:
    dev:
      account: DMIPNKZ-DE16302
      database: AIRBNB
      password: LinkinPark123*
      role: ACCOUNTADMIN
      schema: dbt_schema
      threads: 1
      type: snowflake
      user: shahidsajid1998
      warehouse: COMPUTE_WH
  target: dev
yfinance_dbt:
  outputs:
    dev:
      account: DMIPNKZ-DE16302
      database: YFINANCE_DB
      password: '12345'
      role: DBT_TRANSFORMER
      schema: SILVER
      threads: 4
      type: snowflake
      user: dbt_user
      warehouse: COMPUTE_WH
  target: dev
